services:
  server:
    build: .
    image: blackdark93/dockerfiles-jellyfin-trakt-hook:latest
    ports:
      - "5002:5001"
    env_file:
      - .env
    environment:
      CONFIG_DIR: "/config"
    volumes:
      - "./config:/config"
