version: "3.8"
services:
  app:
    image: "az-go:test"
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
